name: Feature request
description: Suggest an improvement.
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Suggested behavior and alternatives
